#pragma once

#include "SkinManager.h"
#include "SkinDialog.h"
#include "SkinMenu.h"
#include "SkinEdit.h"
#include "SkinStatic.h"
#include "SkinButton.h"
#include "SkinHyperLink.h"
#include "SkinComboBox.h"
#include "SkinPictureBox.h"
#include "SkinScrollBar.h"
#include "SkinToolBar.h"
#include "SkinTabCtrl.h"
#include "SkinListCtrl.h"
#include "SkinRichEdit.h"
#include "SkinMessageBox.h"
#include "SkinWebBrowser.h"
